#-----------------------------------------------------------------------------
# Copyright (c) 2011 Semiconductor Components Industries, LLC
# (d/b/a ON Semiconductor). All Rights Reserved.
#
# This code is the property of ON Semiconductor and may not be redistributed
# in any form without prior written permission from ON Semiconductor. The
# terms of use and warranty for this code are covered by contractual
# agreements between ON Semiconductor and the licensee.
#-----------------------------------------------------------------------------
# Makefile
# - Sample code project Makefile
#-----------------------------------------------------------------------------
# $Revision: 1.2 $
# $Date: 2012/04/17 20:35:16 $
#-----------------------------------------------------------------------------

LEVEL = ../..
APP = eepromlib
BUILD_LIBRARY = 1

include $(LEVEL)/Makefile.rules
