#-----------------------------------------------------------------------------
# Copyright (c) 2012 Semiconductor Components Industries, LLC
# (d/b/a ON Semiconductor). All Rights Reserved.
#
# This code is the property of ON Semiconductor and may not be redistributed
# in any form without prior written permission from ON Semiconductor. The
# terms of use and warranty for this code are covered by contractual
# agreements between ON Semiconductor and the licensee.
#-----------------------------------------------------------------------------
# Makefile
# - Sample code project Makefile
#-----------------------------------------------------------------------------
# $Revision: 1.3 $
# $Date: 2012/04/26 18:50:00 $
#-----------------------------------------------------------------------------

LEVEL = ../../..
SRCDIR = ..
APP = blinky
LIBS = syslib

include $(LEVEL)/Makefile.rules
